sudo: required
services:
  - docker

before_install:
  - docker build -t yamongski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yamongski/react-test npm run test

after_success:
  - docker build -t yamongski/multi-client ./client
  - docker build -t yamongski/multi-nginx ./nginx
  - docker build -t yamongski/multi-server ./server
  - docker build -t yamongski/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to dockerhub
  - docker push yamongski/multi-worker
  - docker push yamongski/multi-nginx
  - docker push yamongski/multi-server
  - docker push yamongski/multi-client

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-687782260860"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
